/**
* Generated by PluginGenerator from webgme on Tue Oct 28 2014 21:14:58 GMT-0500 (CDT).
*/

define([], function () {
    'use strict';
    return {
        'Assembly': '/1341672475/327772930',
        'Component': '/1341672475/2066633787',
        'Connection': '/1341672475/2099752985',
        'Driver': '/1341672475/1239718134',
        'Input': '/1341672475/1752794449',
        'IO': '/1341672475/1590347901',
        'MetaLanguage': '/1341672475',
        'Output': '/1341672475/1639249403',
        'Workflow': '/1341672475/377557448',
    };
});