/**
* Generated by PluginGenerator from webgme on Tue Nov 04 2014 22:56:06 GMT-0600 (CST).
*/

define([], function () {
    'use strict';
    return {
        'Assembly': '/506965338/1135469800',
        'C_IN': '/506965338/223935600',
        'c_input': '/506965338/381808471',
        'C_OUT': '/506965338/651638879',
        'c_output': '/506965338/758513781',
        'Component': '/506965338/1281655630',
        'D_IN': '/506965338/1612711208',
        'D_OUT': '/506965338/813422757',
        'Driver': '/506965338/441602185',
        'MetaLanguage': '/506965338',
    };
});