/* Generated file based on ejs templates */
define([], function() {
    return {
    "Python.py.ejs": "print \"<%=a%> and <%=b%> provided.\"",
    "assembly.py.ejs": "# Auto-generated by the OpenMDAO plugin for WebGME\n# Modify at your own risk\n\nfrom openmdao.main.api import Assembly\n<% components.forEach(function(component) { %>\nfrom <%= component.package %> import <%= component.name %>\n<% }) %>\n\nclass <%= name %>(Assembly):\n\n    def configure(self):\n        <% components.forEach(function(component) { %>\n        self.add('<%= component.name.toLowerCase() %>', <%= component.name %>())\n        <% }) %>\n\n        self.driver.workflow.add([\n            <% components.forEach(function(component) { %>\n            '<%= component.name.toLowerCase() %>',\n            <% }) %>\n        ])"
}});